name: test web hook
on: 
  workflow_dispatch:
jobs:
  send:
    name: send to
    runs-on: ubuntu-latest
    steps:
      - name: Generate, mask, and output a secret
        id: action-hosting-deploy
        run: |
          details_url="https://arbitragescan--pr739-bugfix-flashloan-tre-nn916ynn.web.app"
          echo "::add-mask::$details_url"
          echo "details_url=$details_url" >> "$GITHUB_OUTPUT"
      - name: Invoke Feishu hook
        run: |
          curl --location '${{ secrets.WEBHOOK_URL }}' \
          --header 'Content-Type: application/json' \
          --data '{
              "msg_type": "text",
              "content": {
                  "text": "PR Preview Live at: \n${{ steps.action-hosting-deploy.outputs.details_url }}"
              }
          }'
